### ISSUE TITLE
"vae_EM_idx1.h5" seems missing.

### ISSUE THREAD

**Issue by Szanzang** [ricardoborsoi/Unmixing_with_Deep_Generative_Models#2]
In loadNetworks.m, when execute the following code,
hinfo = hdf5info([baseFilename num2str(em) '.h5'])
an error said cannot find "vae_EM_idx1.h5". 
So I wondered where I could find the file or if it is because I ran the codes wrongly.
Could you please give some guidance? thanks

**Comment by ricardoborsoi** [comment]
Hello,
This file is generated and saved by the python function ```vae_keras_ems_train.py``` that trains the generative models, so there are two main possibilities for this error:  
1. the file was saved in a different folder (changes in the folder structure could cause this)
2. there was an error during the execution of the python code when called from MATLAB. 

Can you check the result of the MATLAB prompt before this error, or when you execute ```system('python python/vae_keras_ems_train.py')``` from MATLAB while in the base directory?

**Comment by Szanzang** [comment]
Thank you for your quick reply!
The problem is solved. 
not sure why local path doesnot work. but when I change it to a global path, the codes can run.
Thank you

**Comment by ricardoborsoi** [comment]
Thanks, I'm happy to know the codes are now working!
