### ISSUE TITLE
suggestion solution on an issue

### ISSUE THREAD

**Issue by khalidcoding** [ricardoborsoi/Unmixing_with_Deep_Generative_Models#3]
<img width="679" alt="Screenshot 2023-03-22 at 18 38 39" src="https://user-images.githubusercontent.com/123639564/226958194-998fc700-99c9-41a6-909f-9bfb85b39a81.png">
Good evening, 
I got this issue related to arrays have imcompatible sizes, please I tried fixing it but every time I get more errors, I know it's a simple error but I'm just new in learning matlab and coding, so if you could help me it will be much appreciate it. 
<img width="624" alt="Screenshot 2023-03-22 at 18 41 26" src="https://user-images.githubusercontent.com/123639564/226959555-49f3ba18-40cb-4668-99d5-344b23e1c2e9.png">

thank you.

**Comment by ricardoborsoi** [comment]
Hi @khalidcoding,  have you checked the sizes of the variables ```Mvs``` and ```M_DeepGen``` to see if they are the same? You can do this by running the commands ```size(Mvs)``` and ```size(M_DeepGen)``` on the Matlab prompt right after you get the error and see what is the result.

Also, was the image ```r_cube``` cropped or modified before being passed to the ```DeepGUn``` function? 
Thanks

**Comment by khalidcoding** [comment]
Hi @ricardoborsoi,
yes I already checked the sizes of Mvs and M_DeepGen, Mvs has (224×3×4900) and M_DeepGen has (345×3×4900), 
 Also the image r_cube hasn't been cropped or modified, "r_cube has (70×70×345) data size".

**Comment by ricardoborsoi** [comment]
Hi @khalidcoding, there is some problem with the dimension of ```r_cube```, it should be 70x70x224 (it is the hyperspectral image, with dimension height by width by bands). This variable (which is the hyperspectral image) is loaded directly from the file ```data_ex1.mat```, provided in the repository:
```
>> load('data/data_ex1.mat')
>> size(r_cube)
ans =
    70    70   224 
```
Please try to compare your version of the code to the latest version of ```example1.m```  in the repository to see if there were any changes to this variable, or to the contents of the file ```data_ex1.mat```.

**Comment by khalidcoding** [comment]
Hello @ricardoborsoi, yes I noticed that I'm using another hyperspectral image data but the thing is when i use this particular r_cube I get a whole bunch of other errors as the picture below
<img width="991" alt="Screenshot 2023-03-28 at 18 49 53" src="https://user-images.githubusercontent.com/123639564/228303012-7d31d088-9aa4-4507-a0e4-8751356d9ac8.png">
thank you for your help, I will try harder with it and let you know the result.
sorry for the late reply.

**Comment by ricardoborsoi** [comment]
Hi @khalidcoding , if you are using a different hyperspectral image, there are a few things to consider:
1. the variable ```Mvs``` contains the ground truths for the endmembers, if this is not available for the image you are considering you might have to ignore the  lines where it is used to evaluate the endmembers RMSE.  
2. You need to extract the reference endmembers (which are stored in ```M0``` of size bands * number of materials) for your new image, using the command ```M0 = vca(r,'Endmembers',P);```, where ```r``` is the new hyperspectral image ordered as (bands * pixels) and ```P``` is the number of materials in the scene.

**Comment by khalidcoding** [comment]
Hi @ricardoborsoi , hope you're doing well.
I couldn't fix this issue I have so I changed my data to the original one (the one you used ) and now this new error pops up and it's about using hdf5info and that 'vae_EM_idx1.h5' could not be open as shown bellow 
<img width="980" alt="Screenshot 2023-04-13 at 12 11 58" src="https://user-images.githubusercontent.com/123639564/231713500-c2455857-59db-4dc6-a2e2-82bcc779bf5b.png">
knowing that the file is saved in the same folder, please if you could give some guidance to fix it I would appreciat it.

**Comment by ricardoborsoi** [comment]
Hello @khalidcoding, this error is most likely caused by the inability to run the ```python``` terminal command from Matlab, see the line ```system('python python/vae_keras_ems_train.py')``` in the function ```DeepGUn/train_DeepGen_EM_model.m```. This is shown through the ```command not found: python``` message.

Fixing it might depend on your operating system, but if you have [Anaconda](https://www.anaconda.com) already installed and are still getting a "python not found" error, you basically have to "tell" Matlab where your python installation is in your system:

1.  First you need the path to python (e.g., Anaconda) in your system, in unix environments you can open a terminal and type "which python", this will show the path to python on your system, for example, ```/Users/myusername/opt/anaconda3/bin/python```. 
2. The you add this path to your Matlab path, using ```setenv('PATH', [getenv('PATH') ':/Users/myusername/opt/anaconda3/bin'])``` (substituting ```myusername``` by the username/path in your case). 
3. You can use ```system('echo $PATH')``` in Matlab to check if python is now present in the path, if so you should be able to run python scripts using ```system("python ...")``` in Matlab.

**Comment by khalidcoding** [comment]
Hello @ricardoborsoi , I don't actually have anaconda in mac mac book, I will try this guidance now and let you know the result, thank you.
at first it was working well without anaconda I had only an error in matrix dimensions, now when I downloaded your code and data version, this error pops up, I don't know why. 
In 2. do I need to add this path to the matlab code path or matlab path in general ?
